name: calendar_application
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  animate_do: ^3.3.4
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  rive_animated_icon: ^2.0.3
  table_calendar: ^3.1.3
  http: ^1.2.2
  animated_analog_clock: ^0.1.0
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/dark_bg.png
    - assets/images/light_bg.png
    - assets/images/light-1.png
    - assets/images/light-2.png
    - assets/images/clock.png
    - assets/lottie_animation/Hello.json
    - assets/lottie_animation/success.lottie
    - assets/lottie_animation/success.json
    - assets/lottie_animation/loading.json
    - assets/lottie_animation/dark_loading.json
    - assets/lottie_animation/mixed_loading.json
